### ISSUE TITLE
Undersøk og fiks problemer med off days (potensielt andre events også) i period summary view

### ISSUE THREAD

**Issue by Hallvats** [Gunnerus/gunnerus#421]
![Screenshot_2021-02-12 R V Gunnerus Reservation System(1)](https://user-images.githubusercontent.com/17251472/107794127-59bbe300-6d57-11eb-8f9c-012afb55e525.png)
------------------
![Screenshot_2021-02-12 R V Gunnerus Reservation System](https://user-images.githubusercontent.com/17251472/107793171-4d835600-6d56-11eb-8749-604df6f8cafb.png)
------------------
Blir generert flere overskrifter av samme dag og duplikate events når det er flere events på samme dag.

**Comment by Hallvats** [comment]
get_days_with_events(events) i utils som lager like mange av samme dag som det er events den dagen

**Comment by Hallvats** [comment]
Lukker denne inntil videre. Fikset duplikate dager, men vet ikke om det trengs en fiks for at events som varer flere dager kun vises i første og siste dag.

**Comment by AudunVN** [comment]
> Lukker denne inntil videre. Fikset duplikate dager, men vet ikke om det trengs en fiks for at events som varer flere dager kun vises i første og siste dag.

Vil si at det er et problem om det gjør at events ikke dukker opp i det hele tatt om man ser på en periode som er i mellom start- og sluttidspunktet til hendelsen? Usikker på om dette er tilfelle.
